# Generated by Django 4.2.30 on 2026-04-12 19:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientCase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('case_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('visit_type', models.CharField(default='New medical issue', max_length=100)),
                ('body_location', models.CharField(blank=True, max_length=100)),
                ('symptom_duration', models.CharField(blank=True, max_length=100)),
                ('symptoms_text', models.TextField(help_text="Patient's description of symptoms")),
                ('selected_symptoms', models.JSONField(blank=True, default=list, help_text='Structured symptom selections')),
                ('severity_symptoms', models.JSONField(blank=True, default=list, help_text='Severity/red-flag symptoms selected')),
                ('additional_info', models.TextField(blank=True)),
                ('previous_treatment', models.BooleanField(default=False)),
                ('previously_seen', models.BooleanField(default=False)),
                ('ai_urgency', models.CharField(blank=True, choices=[('emergency', 'Emergency (999/A&E)'), ('urgent', 'Urgent (1-2 days)'), ('routine', 'Routine (2-3 weeks)'), ('self_care', 'Self-care / Non-urgent')], help_text='AI-suggested urgency level', max_length=20)),
                ('ai_confidence', models.FloatField(blank=True, help_text='AI confidence score (0-1)', null=True)),
                ('ai_rationale', models.TextField(blank=True, help_text='AI explanation for the suggested urgency')),
                ('ai_differential', models.JSONField(blank=True, default=list, help_text='AI differential diagnosis suggestions')),
                ('clinician_urgency', models.CharField(blank=True, choices=[('emergency', 'Emergency (999/A&E)'), ('urgent', 'Urgent (1-2 days)'), ('routine', 'Routine (2-3 weeks)'), ('self_care', 'Self-care / Non-urgent')], help_text="Clinician's final urgency decision", max_length=20)),
                ('clinician_notes', models.TextField(blank=True)),
                ('clinician_decision_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('new', 'New Patient Case'), ('in_progress', 'In Progress (Clinician Reviewing)'), ('decided', 'Decided (Awaiting Navigator Action)'), ('closed', 'Closed')], default='new', max_length=20)),
                ('closure_reason', models.CharField(blank=True, choices=[('appointment_booked', 'Appointment Booked'), ('urgent_referral', 'Urgent Referral (A&E/999)'), ('follow_up', 'Follow-up Appointment'), ('self_care_advised', 'Self-care Advised'), ('referred_111', '111 Referral'), ('extended_access', 'Extended Access'), ('no_contact_required', 'No Contact Required'), ('message_sent', 'Message Sent to Patient'), ('other', 'Other')], max_length=30)),
                ('closure_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_handler', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_cases', to=settings.AUTH_USER_MODEL)),
                ('clinician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triaged_cases', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Case Created'), ('ai_triaged', 'AI Triage Completed'), ('clinician_reviewed', 'Clinician Reviewed'), ('clinician_decided', 'Clinician Decision Made'), ('redirected', 'Redirected to Another Unit'), ('navigator_actioned', 'Care Navigator Action Taken'), ('closed', 'Case Closed'), ('reopened', 'Case Reopened'), ('note_added', 'Note Added')], max_length=30)),
                ('details', models.TextField(blank=True)),
                ('previous_status', models.CharField(blank=True, max_length=20)),
                ('new_status', models.CharField(blank=True, max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='cases.patientcase')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
